# =============================================================================
# File        : pinout.xdc
# Project     : 32-Bit Custom FPGA Microcontroller
# Description : Xilinx Physical Constraints File (XDC) for Basys 3 board
# =============================================================================

# System Clock (100 MHz oscillator)
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]

# System Reset (Active Low, using Center Push Button)
set_property PACKAGE_PIN U18 [get_ports rst_n]						
	set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

# UART (JA Pmod Header pins 1 & 2)
# JA1 (Pin B13) -> RX
# JA2 (Pin F13) -> TX
set_property PACKAGE_PIN B13 [get_ports rx]						
	set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN F13 [get_ports tx]						
	set_property IOSTANDARD LVCMOS33 [get_ports tx]

# GPIO Pins (Mapped to 16 Onboard LEDs for output and 16 Onboard Switches for input)
# gp_in[15:0] (Switches)
set_property PACKAGE_PIN V17 [get_ports {gp_in[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {gp_in[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {gp_in[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {gp_in[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {gp_in[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {gp_in[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {gp_in[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {gp_in[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {gp_in[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {gp_in[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {gp_in[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {gp_in[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {gp_in[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {gp_in[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {gp_in[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {gp_in[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_in[15]}]
# Pullups for unused gp_in
set_property -dict { PACKAGE_PIN J1   IOSTANDARD LVCMOS33 } [get_ports {gp_in[16]}]
set_property -dict { PACKAGE_PIN L2   IOSTANDARD LVCMOS33 } [get_ports {gp_in[17]}]
set_property -dict { PACKAGE_PIN J2   IOSTANDARD LVCMOS33 } [get_ports {gp_in[18]}]
set_property -dict { PACKAGE_PIN G2   IOSTANDARD LVCMOS33 } [get_ports {gp_in[19]}]
set_property -dict { PACKAGE_PIN H1   IOSTANDARD LVCMOS33 } [get_ports {gp_in[20]}]
set_property -dict { PACKAGE_PIN K1   IOSTANDARD LVCMOS33 } [get_ports {gp_in[21]}]
set_property -dict { PACKAGE_PIN H2   IOSTANDARD LVCMOS33 } [get_ports {gp_in[22]}]
set_property -dict { PACKAGE_PIN G3   IOSTANDARD LVCMOS33 } [get_ports {gp_in[23]}]
set_property -dict { PACKAGE_PIN L3   IOSTANDARD LVCMOS33 } [get_ports {gp_in[24]}]
set_property -dict { PACKAGE_PIN M3   IOSTANDARD LVCMOS33 } [get_ports {gp_in[25]}]
set_property -dict { PACKAGE_PIN M2   IOSTANDARD LVCMOS33 } [get_ports {gp_in[26]}]
set_property -dict { PACKAGE_PIN N2   IOSTANDARD LVCMOS33 } [get_ports {gp_in[27]}]
set_property -dict { PACKAGE_PIN K3   IOSTANDARD LVCMOS33 } [get_ports {gp_in[28]}]
set_property -dict { PACKAGE_PIN L4   IOSTANDARD LVCMOS33 } [get_ports {gp_in[29]}]
set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports {gp_in[30]}]
set_property -dict { PACKAGE_PIN J4   IOSTANDARD LVCMOS33 } [get_ports {gp_in[31]}]

# gp_out[15:0] (LEDs)
set_property PACKAGE_PIN U16 [get_ports {gp_out[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {gp_out[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {gp_out[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {gp_out[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {gp_out[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {gp_out[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {gp_out[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {gp_out[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[7]}]
set_property PACKAGE_PIN V13 [get_ports {gp_out[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {gp_out[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {gp_out[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {gp_out[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {gp_out[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {gp_out[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[13]}]
set_property PACKAGE_PIN P1 [get_ports {gp_out[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[14]}]
set_property PACKAGE_PIN L1 [get_ports {gp_out[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {gp_out[15]}]

# Seven Segment Display Digit Drive
set_property PACKAGE_PIN W4 [get_ports {anodes[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]
set_property PACKAGE_PIN V4 [get_ports {anodes[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property PACKAGE_PIN U4 [get_ports {anodes[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property PACKAGE_PIN U2 [get_ports {anodes[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]

set_property PACKAGE_PIN W7 [get_ports {segments[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property PACKAGE_PIN W6 [get_ports {segments[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property PACKAGE_PIN U8 [get_ports {segments[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property PACKAGE_PIN V5 [get_ports {segments[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property PACKAGE_PIN U7 [get_ports {segments[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property PACKAGE_PIN V7 [get_ports {segments[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[7]}]

# System watchdog status output
set_property PACKAGE_PIN N3 [get_ports system_reset_out]
	set_property IOSTANDARD LVCMOS33 [get_ports system_reset_out]
